"""Tests for /api/pyqs/answer (on-demand exam answer generation)."""

from __future__ import annotations

import uuid
from io import BytesIO

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, event
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.core.security import create_access_token, hash_password
from app.db.base import Base
from app.db.session import get_db
from app.models import StudyMaterial, User
from main import app
from rag.context_builder import build_exam_answer_prompt, build_exam_directive
from rag.llm.base import (
    LLMResponse,
    LLMTimeoutError,
    LLMUnavailableError,
)
from rag.llm.mock_provider import MockProvider
from rag.models import ChunkMetadata, SearchResult
from rag.pyq_answer import (
    DEFAULT_MIN_RELEVANCE_SCORE,
    max_tokens_for_marks,
    relevant_results,
)
from app.api.routes.chat import get_llm_provider as chat_get_llm_provider

TEST_PASSWORD = "testpassword123"

test_engine = create_engine(
    "sqlite://",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)


@event.listens_for(test_engine, "connect")
def _enable_fk(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()


TestingSession = sessionmaker(
    bind=test_engine, autoflush=False, autocommit=False, expire_on_commit=False
)


def _reset() -> None:
    Base.metadata.drop_all(bind=test_engine)
    Base.metadata.create_all(bind=test_engine)


def _make_user(name: str, email: str) -> User:
    db = TestingSession()
    user = User(name=name, email=email, password_hash=hash_password(TEST_PASSWORD))
    db.add(user)
    db.commit()
    db.refresh(user)
    db.close()
    return user


def _create_course(client, headers, name="Biology", code="BIO101") -> dict:
    response = client.post(
        "/api/courses", json={"name": name, "code": code}, headers=headers
    )
    assert response.status_code == 201
    return response.json()


def _upload_and_process(client, headers, course_id, *, title="Biology Notes", content) -> dict:
    response = client.post(
        "/api/materials/upload",
        data={"course_id": course_id, "title": title, "material_type": "notes"},
        files={"file": ("notes.txt", BytesIO(content.encode()), "text/plain")},
        headers=headers,
    )
    assert response.status_code == 201
    material = response.json()
    process = client.post(
        f"/api/materials/{material['id']}/process", headers=headers
    )
    assert process.status_code == 200
    assert process.json()["status"] == "processed"
    return material


@pytest.fixture()
def client(tmp_path, monkeypatch):
    """Client with a deterministic mock LLM and an isolated RAG store."""
    monkeypatch.setenv("STORAGE_DIR", str(tmp_path / "storage"))
    from app.core.config import get_settings

    get_settings.cache_clear()
    _reset()

    mock_llm = MockProvider(default_answer="Model answer generated by the mock.")

    def override_get_db():
        db = TestingSession()
        try:
            yield db
        finally:
            db.close()

    def override_llm():
        return mock_llm

    app.dependency_overrides[get_db] = override_get_db
    app.dependency_overrides[chat_get_llm_provider] = override_llm

    with TestClient(app) as c:
        yield c, mock_llm

    app.dependency_overrides.clear()
    get_settings.cache_clear()


def _upload_pyq(client, headers, course_id, *, title, content, name="pyq.txt") -> dict:
    """Upload a question paper the same way the PYQ page does."""
    response = client.post(
        "/api/materials/upload",
        data={"course_id": course_id, "title": title, "material_type": "pyq"},
        files={"file": (name, BytesIO(content.encode()), "text/plain")},
        headers=headers,
    )
    assert response.status_code == 201
    return response.json()


class TestAnalyzeReporting:
    """/api/pyqs/analyze must let the frontend tell failure modes apart."""

    def test_requires_auth(self, client) -> None:
        c, _ = client
        resp = c.post("/api/pyqs/analyze", json={"num_questions": 5})
        assert resp.status_code in (401, 403)

    def test_reports_analyzed_and_failed_files(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)

        good = _upload_pyq(
            c,
            headers,
            course["id"],
            title="2024 Paper",
            name="paper2024.txt",
            content=(
                "1. Explain TCP and UDP.\n"
                "2. Explain CSMA/CD in detail.\n"
                "3. Differentiate OSI and TCP/IP models.\n"
            ),
        )
        # A file that does not exist on disk is reported as a failure.
        missing = _upload_pyq(
            c,
            headers,
            course["id"],
            title="Missing Paper",
            name="paper2025.txt",
            content="1. Explain queuing networks.",
        )
        db = TestingSession()
        row = db.get(StudyMaterial, uuid.UUID(missing["id"]))
        row.stored_file_name = "does-not-exist.txt"
        db.commit()
        db.close()

        resp = c.post(
            "/api/pyqs/analyze",
            json={
                "course_id": course["id"],
                "num_questions": 10,
                "file_ids": [good["id"], missing["id"]],
            },
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["analyzed_files"] == ["paper2024.txt"]
        assert len(data["failed_files"]) == 1
        assert data["summary"]["papers_failed"] == 1
        assert data["summary"]["papers_analyzed"] == 1
        # Real questions are returned; none are fabricated.
        assert data["total_questions"] >= 1
        assert all(q["question"] for q in data["questions"])

    def test_empty_paper_reports_zero_questions_not_an_error(
        self, client
    ) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)

        paper = _upload_pyq(
            c,
            headers,
            course["id"],
            title="Blank Paper",
            content="Some notes that contain no questions at all.",
        )

        resp = c.post(
            "/api/pyqs/analyze",
            json={"course_id": course["id"], "file_ids": [paper["id"]]},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        # Read successfully, but nothing extractable: distinct from a failure.
        assert data["analyzed_files"] == ["pyq.txt"]
        assert data["failed_files"] == []
        assert data["questions"] == []

    def test_unknown_file_id_is_reported_not_ignored(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        resp = c.post(
            "/api/pyqs/analyze",
            json={"file_ids": [str(uuid.uuid4())]},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["analyzed_files"] == []
        assert len(data["failed_files"]) == 1

    def test_another_users_file_is_never_analyzed(self, client) -> None:
        c, _ = client
        alice = _make_user("Alice", "alice@example.com")
        bob = _make_user("Bob", "bob@example.com")
        alice_headers = {"Authorization": f"Bearer {create_access_token(alice.id)}"}
        bob_headers = {"Authorization": f"Bearer {create_access_token(bob.id)}"}

        course = _create_course(c, alice_headers)
        paper = _upload_pyq(
            c,
            alice_headers,
            course["id"],
            title="Alice Paper",
            content="1. Explain TCP congestion control.\n",
        )

        resp = c.post(
            "/api/pyqs/analyze",
            json={"file_ids": [paper["id"]]},
            headers=bob_headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["analyzed_files"] == []
        assert data["questions"] == []
        assert len(data["failed_files"]) == 1

    def test_respects_requested_question_count(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)
        paper = _upload_pyq(
            c,
            headers,
            course["id"],
            title="Big Paper",
            name="big.txt",
            content=(
                "1. Describe the water cycle in detail.\n"
                "2. Explain how a refrigerator removes heat.\n"
                "3. Discuss the causes of atmospheric pressure changes.\n"
                "4. Compare electrical and chemical bonding.\n"
                "5. Outline the life cycle of a butterfly.\n"
                "6. Explain the rules of perspective drawing.\n"
                "7. Summarize the structure of the human kidney.\n"
                "8. Describe how clouds form from evaporation.\n"
            ),
        )

        resp = c.post(
            "/api/pyqs/analyze",
            json={
                "course_id": course["id"],
                "file_ids": [paper["id"]],
                "num_questions": 5,
            },
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["questions"]) == 5
        assert data["total_questions"] >= 5

    def test_rejects_out_of_range_question_count(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        resp = c.post(
            "/api/pyqs/analyze",
            json={"num_questions": 51},
            headers={"Authorization": f"Bearer {create_access_token(user.id)}"},
        )
        assert resp.status_code == 422


class TestQuestionMetadataExtraction:
    """Marks, unit and year must come from the paper, not be left blank."""

    def test_extracts_marks_unit_and_year(self) -> None:
        from app.services.pyq_service import PyqAnalyzer

        analyzer = PyqAnalyzer(knowledge_base=None)
        text = (
            "DCCN Model Paper 2024\n"
            "Unit 1\n"
            "1. Explain TCP and UDP. (10 marks)\n"
            "2. Define congestion control. [5 M]\n"
            "UNIT-II\n"
            "iv. Explain CSMA/CD in detail. (20 marks)\n"
            "5. Differentiate OSI and TCP/IP models. [10]\n"
        )
        entries = analyzer.extract_questions_with_meta(text, year="2024")

        assert len(entries) == 4
        assert entries[0]["marks"] == 10
        assert entries[0]["unit"] == "Unit 1"
        assert entries[1]["marks"] == 5
        assert entries[2]["unit"] == "Unit II"
        assert entries[2]["marks"] == 20
        assert entries[3]["marks"] == 10
        # Unit headings are never treated as questions.
        assert not any(e["text"].lower().startswith("unit") for e in entries)

    def test_year_prefers_filename(self) -> None:
        from app.services.pyq_service import PyqAnalyzer

        analyzer = PyqAnalyzer(knowledge_base=None)
        assert analyzer.extract_paper_year("", "DCCN_2023.pdf") == "2023"
        assert analyzer.extract_paper_year("exam held 2019", "final.txt") == "2019"
        assert analyzer.extract_paper_year("no dates here", None) is None

    def test_no_marks_stated_returns_none(self) -> None:
        from app.services.pyq_service import PyqAnalyzer

        assert PyqAnalyzer.extract_marks("Explain TCP and UDP.") is None

    def test_metadata_reaches_the_response(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)
        paper = _upload_pyq(
            c,
            headers,
            course["id"],
            title="2024 Paper",
            name="DCCN_2024.txt",
            content=(
                "Unit 1\n"
                "1. Explain TCP and UDP. (10 marks)\n"
                "2. Explain CSMA/CD in detail. (20 marks)\n"
            ),
        )

        resp = c.post(
            "/api/pyqs/analyze",
            json={"course_id": course["id"], "file_ids": [paper["id"]]},
            headers=headers,
        )
        assert resp.status_code == 200
        questions = resp.json()["questions"]
        assert questions
        by_text = {q["question"]: q for q in questions}
        tcp = by_text["Explain TCP and UDP. (10 marks)"]
        assert tcp["marks"] == 10
        assert tcp["unit"] == "Unit 1"
        assert tcp["years_appeared"] == ["2024"]
        assert tcp["files"] == ["DCCN_2024.txt"]


class TestSemanticGroupingUsesSharedEmbeddings:
    """Paraphrases must merge via the knowledge base's own embedder."""

    def _analyzer(self):
        import tempfile
        from pathlib import Path

        from rag.embeddings import get_embedder
        from rag.knowledge_base import KnowledgeBase
        from rag.vectorstore.sqlite_store import SqliteVectorStore
        from app.services.pyq_service import PyqAnalyzer

        store = SqliteVectorStore(Path(tempfile.mkdtemp()) / "v.db")
        kb = KnowledgeBase(get_embedder("deterministic"), store)
        return PyqAnalyzer(knowledge_base=kb), kb

    def test_paraphrases_are_merged(self) -> None:
        analyzer, _ = self._analyzer()
        pairs = analyzer.find_similar_questions(
            [
                "Explain TCP and UDP. (10 marks)",
                "Explain the TCP and UDP protocols. (10 marks)",
            ],
            threshold=0.6,
        )
        assert pairs, "paraphrases should be reported as similar"
        i, j, score = pairs[0]
        assert (i, j) == (0, 1)
        assert score >= 0.6

    def test_unrelated_questions_are_not_merged(self) -> None:
        analyzer, _ = self._analyzer()
        pairs = analyzer.find_similar_questions(
            [
                "Explain TCP and UDP. (10 marks)",
                "Describe the water cycle. (5 marks)",
            ],
            threshold=0.99,
        )
        assert pairs == []

    def test_knowledge_base_exposes_embed(self) -> None:
        _, kb = self._analyzer()
        vectors = kb.embed(["hello world", "another phrase"])
        assert len(vectors) == 2
        assert all(len(v) > 0 for v in vectors)

    def test_ranking_prefers_frequency_then_marks(self) -> None:
        from app.services.pyq_service import PyqAnalyzer

        ranked = PyqAnalyzer(knowledge_base=None).rank_questions(
            [
                {"question": "rare big", "frequency": 1, "marks": 20, "importance": "Medium"},
                {"question": "common small", "frequency": 3, "marks": 5, "importance": "High"},
            ],
            5,
        )
        # Frequency dominates: the question seen 3 times outranks a 20-mark one.
        assert ranked[0]["question"] == "common small"

    def test_respects_top_n(self) -> None:
        from app.services.pyq_service import PyqAnalyzer

        ranked = PyqAnalyzer(knowledge_base=None).rank_questions(
            [{"question": f"q{i}", "frequency": i, "marks": 2} for i in range(1, 6)],
            2,
        )
        assert len(ranked) == 2


class TestAnswerAuthentication:
    def test_requires_auth(self, client) -> None:
        c, _ = client
        resp = c.post("/api/pyqs/answer", json={"question": "Explain mitosis."})
        assert resp.status_code in (401, 403)

    def test_rejects_invalid_token(self, client) -> None:
        c, _ = client
        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain mitosis."},
            headers={"Authorization": "Bearer invalid-token"},
        )
        assert resp.status_code == 401

    def test_rejects_blank_question(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "   "},
            headers={"Authorization": f"Bearer {create_access_token(user.id)}"},
        )
        assert resp.status_code == 422

    def test_rejects_invalid_course_id(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain mitosis.", "course_id": "not-a-uuid"},
            headers={"Authorization": f"Bearer {create_access_token(user.id)}"},
        )
        assert resp.status_code == 422

    def test_rejects_out_of_range_marks(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain mitosis.", "marks": 0},
            headers={"Authorization": f"Bearer {create_access_token(user.id)}"},
        )
        assert resp.status_code == 422


class TestAnswerGrounding:
    def test_grounds_answer_in_uploaded_material(self, client) -> None:
        c, mock_llm = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)
        _upload_and_process(
            c,
            headers,
            course["id"],
            content=(
                "Photosynthesis converts light energy into chemical energy. "
                "The Calvin cycle fixes carbon dioxide into glucose inside the "
                "chloroplast stroma of plant cells."
            ),
        )

        resp = c.post(
            "/api/pyqs/answer",
            json={
                "question": "Explain how photosynthesis converts light energy.",
                "course_id": course["id"],
                "marks": 10,
                "answer_format": "Medium",
            },
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["has_context"] is True
        assert len(data["sources"]) >= 1
        assert all(s["course_id"] == str(course["id"]) for s in data["sources"])
        assert data["marks"] == 10
        assert data["answer_format"] == "Medium"
        # The retrieved material must actually reach the model prompt.
        assert "calvin cycle" in mock_llm.last_prompt.lower()

    def test_falls_back_to_general_knowledge_without_material(
        self, client
    ) -> None:
        c, mock_llm = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain quantum entanglement."},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        # The answer is still produced, but provenance must be honest.
        assert data["has_context"] is False
        assert data["sources"] == []
        assert data["answer"].strip() != ""
        assert mock_llm.call_count == 1

    def test_another_users_material_is_not_grounded(self, client) -> None:
        c, _ = client
        alice = _make_user("Alice", "alice@example.com")
        bob = _make_user("Bob", "bob@example.com")
        alice_headers = {"Authorization": f"Bearer {create_access_token(alice.id)}"}
        bob_headers = {"Authorization": f"Bearer {create_access_token(bob.id)}"}

        course = _create_course(c, alice_headers)
        _upload_and_process(
            c,
            alice_headers,
            course["id"],
            content="The Calvin cycle fixes carbon dioxide into glucose.",
        )

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain the Calvin cycle."},
            headers=bob_headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["has_context"] is False
        assert data["sources"] == []

    def test_course_filter_excludes_other_courses(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        bio = _create_course(c, headers, name="Biology", code="BIO101")
        chem = _create_course(c, headers, name="Chemistry", code="CHE101")
        _upload_and_process(
            c,
            headers,
            bio["id"],
            title="Biology Notes",
            content="Photosynthesis converts light energy into chemical energy.",
        )
        _upload_and_process(
            c,
            headers,
            chem["id"],
            title="Chemistry Notes",
            content="Titration measures concentration using a burette and indicator.",
        )

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Describe photosynthesis.", "course_id": bio["id"]},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["has_context"] is True
        assert all(s["course_id"] == str(bio["id"]) for s in data["sources"])
        assert data["course_name"] == "Biology"


class TestAnswerExamShaping:
    def test_prompt_reflects_marks_and_format(self, client) -> None:
        c, mock_llm = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        resp = c.post(
            "/api/pyqs/answer",
            json={
                "question": "Describe the OSI model.",
                "marks": 20,
                "answer_format": "Exam-Oriented",
                "styles": {"point_wise": True, "include_diagrams": True},
            },
            headers=headers,
        )
        assert resp.status_code == 200
        prompt = mock_llm.last_prompt
        assert "Marks: 20" in prompt
        assert "20-mark slot" in prompt
        assert "Exam-Oriented" in prompt
        assert "point-wise bullets" in prompt
        assert "diagram" in prompt.lower()

    def test_token_budget_scales_with_marks(self, client) -> None:
        c, mock_llm = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        c.post(
            "/api/pyqs/answer",
            json={"question": "Define a protocol.", "marks": 2},
            headers=headers,
        )
        short_budget = mock_llm.last_max_tokens

        c.post(
            "/api/pyqs/answer",
            json={"question": "Define a protocol.", "marks": 20},
            headers=headers,
        )
        long_budget = mock_llm.last_max_tokens

        assert short_budget < long_budget
        assert max_tokens_for_marks(2) == 350
        assert max_tokens_for_marks(20) == 1600
        assert max_tokens_for_marks(None) == 700

    def test_llm_failure_is_an_http_error_not_a_fake_answer(self, client) -> None:
        """A failed generation must never come back as 200 with error text."""
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        class FailingLLM(MockProvider):
            def generate(self, *args, **kwargs):  # type: ignore[override]
                raise LLMUnavailableError(
                    "The language model is temporarily unavailable."
                )

        app.dependency_overrides[chat_get_llm_provider] = lambda: FailingLLM()

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain CSMA/CD."},
            headers=headers,
        )
        assert resp.status_code == 503
        # The body must be an error detail, not an "answer" field.
        assert "answer" not in resp.json()

    def test_llm_timeout_returns_504(self, client) -> None:
        """A slow model is a gateway timeout, not an outage and not a 200."""
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        class TimingOutLLM(MockProvider):
            def generate(self, *args, **kwargs):  # type: ignore[override]
                raise LLMTimeoutError(
                    "The language model took longer than 300s to answer."
                )

        app.dependency_overrides[chat_get_llm_provider] = lambda: TimingOutLLM()

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain CSMA/CD.", "marks": 10},
            headers=headers,
        )
        assert resp.status_code == 504
        detail = resp.json()["detail"].lower()
        assert "too long" in detail or "took too long" in detail
        # Must not claim the model is unavailable: it was reachable.
        assert "temporarily unavailable" not in detail

    def test_unexpected_llm_exception_is_not_reported_as_an_answer(
        self, client
    ) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        class CrashingLLM(MockProvider):
            def generate(self, *args, **kwargs):  # type: ignore[override]
                raise ValueError("totally unexpected")

        app.dependency_overrides[chat_get_llm_provider] = lambda: CrashingLLM()

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain CSMA/CD."},
            headers=headers,
        )
        assert resp.status_code == 503
        assert "answer" not in resp.json()

    def test_empty_completion_is_an_error(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}

        class EmptyLLM(MockProvider):
            def generate(self, *args, **kwargs):  # type: ignore[override]
                return LLMResponse(text="   ", model="qwen2.5-coder:7b")

        app.dependency_overrides[chat_get_llm_provider] = lambda: EmptyLLM()

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain CSMA/CD."},
            headers=headers,
        )
        assert resp.status_code == 503
        assert "answer" not in resp.json()


class TestRelevanceThreshold:
    def _result(self, score: float, chunk_id: str = "c") -> SearchResult:
        return SearchResult(
            chunk_id=chunk_id,
            material_id="m1",
            course_id="c1",
            uploaded_by="u1",
            text="some chunk text",
            score=score,
            metadata=ChunkMetadata(
                material_id="m1",
                course_id="c1",
                material_title="Notes",
                original_filename="notes.pdf",
                chunk_index=0,
                total_chunks=1,
            ),
        )

    def test_keeps_relevant_and_drops_noise(self) -> None:
        results = [self._result(0.9, "a"), self._result(0.12, "b")]
        kept = relevant_results(results)
        assert [r.chunk_id for r in kept] == ["a"]

    def test_threshold_boundary_is_inclusive(self) -> None:
        results = [self._result(DEFAULT_MIN_RELEVANCE_SCORE)]
        assert len(relevant_results(results)) == 1
        assert len(relevant_results(results, DEFAULT_MIN_RELEVANCE_SCORE + 0.01)) == 0

    def test_empty_results_stay_empty(self) -> None:
        assert relevant_results([]) == []


class TestExamPromptBuilder:
    def test_no_context_uses_general_knowledge_prompt(self) -> None:
        system, user = build_exam_answer_prompt(
            "Explain CSMA/CD.", [], marks=5, answer_format="Short"
        )
        assert "general knowledge" in system.lower()
        assert "[Source 1]" not in user
        assert "Marks: 5" in user
        assert "Short" in user

    def test_context_includes_sources_and_delimiters(self) -> None:
        metadata = ChunkMetadata(
            material_id="m1",
            course_id="c1",
            material_title="Unit 3",
            original_filename="unit3.pdf",
            chunk_index=2,
            total_chunks=9,
            page=7,
        )
        result = SearchResult(
            chunk_id="c",
            material_id="m1",
            course_id="c1",
            uploaded_by="u1",
            text="CSMA/CD detects collisions using binary exponential backoff.",
            score=0.81,
            metadata=metadata,
        )
        system, user = build_exam_answer_prompt(
            "Explain collision detection.", [result], marks=10, answer_format="Detailed"
        )
        assert "Source 1" in user
        assert "Unit 3" in user
        assert "binary exponential backoff" in user
        assert "exam answer writer" in system.lower()

    def test_directive_omits_absent_course(self) -> None:
        directive = build_exam_directive(
            marks=None, answer_format=None, course_name=None, styles=None
        )
        assert "not specified" in directive.lower()
        assert "Course:" not in directive

    def test_directive_ignores_unknown_styles(self) -> None:
        directive = build_exam_directive(
            marks=10,
            answer_format="Short",
            course_name="DCCN",
            styles={"not_a_real_style": True},
        )
        assert "Additional style requirements" not in directive


class TestPyqMetadataNeverGroundsAnswers:
    """PYQ frequency/repetition/ranking data must not leak into answer context.

    The spec separates the two roles: question papers drive analysis only, and
    only study materials may ground an answer.
    """

    def test_answer_prompt_has_no_field_for_pyq_statistics(self) -> None:
        import inspect

        from rag.pyq_answer import answer_pyq_question

        params = set(inspect.signature(answer_pyq_question).parameters)
        # The service must not even accept PYQ statistics as input.
        assert not params & {
            "frequency",
            "years",
            "years_appeared",
            "importance",
            "repetition",
            "pyq_data",
            "rank",
        }

    def test_pyq_prompt_never_repeats_analysis_statistics(self, client) -> None:
        c, mock_llm = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)
        _upload_and_process(
            c,
            headers,
            course["id"],
            content=(
                "TCP provides connection-oriented reliable delivery with "
                "sequence numbers and acknowledgements. UDP is connectionless "
                "and offers no delivery or ordering guarantees."
            ),
        )

        resp = c.post(
            "/api/pyqs/answer",
            json={
                "question": "Explain TCP and UDP.",
                "course_id": course["id"],
                "marks": 10,
                "answer_format": "Medium",
            },
            headers=headers,
        )
        assert resp.status_code == 200
        assert resp.json()["has_context"] is True

        prompt = mock_llm.last_prompt.lower()
        # Study-material content is present...
        assert "sequence numbers" in prompt
        # ...but no analysis statistic is used as grounding context.
        assert "frequency" not in prompt
        assert "years appeared" not in prompt
        assert "importance" not in prompt
        assert "repeated" not in prompt


class TestPyqMaterialsAreNotGroundingSources:
    """Question papers feed analysis only and must stay out of the RAG index."""

    def test_type_classification(self) -> None:
        from app.services.study_material_service import (
            is_pyq_material_type,
            is_rag_grounding_material,
        )

        for value in ("pyq", "PYQ", "Question Paper", "question_bank", "pyq_paper"):
            assert is_pyq_material_type(value) is True
            assert is_rag_grounding_material(value) is False

        for value in ("notes", "ppt", "pdf", "module_notes", None, ""):
            assert is_pyq_material_type(value) is False
            assert is_rag_grounding_material(value) is True

    def test_pyq_upload_is_processed_but_not_retrievable(self, client) -> None:
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)

        upload = c.post(
            "/api/materials/upload",
            data={
                "course_id": course["id"],
                "title": "2024 Question Paper",
                "material_type": "pyq",
            },
            files={
                "file": (
                    "pyq2024.txt",
                    BytesIO(
                        b"1. Explain TCP and UDP. "
                        b"2. Explain CSMA/CD in detail. "
                        b"3. Differentiate OSI and TCP IP models."
                    ),
                    "text/plain",
                )
            },
            headers=headers,
        )
        assert upload.status_code == 201
        material = upload.json()

        process = c.post(f"/api/materials/{material['id']}/process", headers=headers)
        assert process.status_code == 200
        assert process.json()["status"] == "processed"

        # The paper is readable (processed), yet it must not ground an answer.
        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain TCP and UDP.", "course_id": course["id"]},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["has_context"] is False
        assert data["sources"] == []
        assert data["answer"].strip() != ""

    def test_same_content_as_study_material_is_retrievable(self, client) -> None:
        """Control case: proves the PYQ exclusion is what causes the miss.

        Without this, the previous test could pass simply because retrieval was
        broken for this content in general.
        """
        c, _ = client
        user = _make_user("Alice", "alice@example.com")
        headers = {"Authorization": f"Bearer {create_access_token(user.id)}"}
        course = _create_course(c, headers)

        _upload_and_process(
            c,
            headers,
            course["id"],
            title="Networking Notes",
            content=(
                "TCP provides connection-oriented reliable delivery with "
                "sequence numbers and acknowledgements."
            ),
        )

        resp = c.post(
            "/api/pyqs/answer",
            json={"question": "Explain TCP and UDP.", "course_id": course["id"]},
            headers=headers,
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["has_context"] is True
        assert len(data["sources"]) >= 1
        assert all(s["material_title"] == "Networking Notes" for s in data["sources"])